version: "3"
services:
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
      args:
        - REACT_APP_SERVER_URL=${REACT_APP_SERVER_URL}
    image: gcr.io/made-by-tim/pokemon-rps-client
    ports:
      - "8080:8080"
  backend:
    build:
      dockerfile: Dockerfile
      context: ./server
    image: gcr.io/made-by-tim/pokemon-rps-server
    environment:
      - MONGODB_URL
    ports:
      - "5000:5000"

  # docker-compose --env-file .env build
  # docker-compose --env-file .env up